#include "CGEKComponentLight.h"

REGISTER_COMPONENT(light)
    REGISTER_COMPONENT_SERIALIZE(light)
        REGISTER_COMPONENT_SERIALIZE_VALUE(color, StrFromFloat3)
        REGISTER_COMPONENT_SERIALIZE_VALUE(range, StrFromFloat)
    REGISTER_COMPONENT_DESERIALIZE(light)
        REGISTER_COMPONENT_DESERIALIZE_VALUE(color, StrToFloat3)
        REGISTER_COMPONENT_DESERIALIZE_VALUE(range, StrToFloat)
END_REGISTER_COMPONENT(light)
