#include "CGEKComponentSize.h"

REGISTER_SIMPLE_COMPONENT(size, float3(1.0f, 1.0f, 1.0f))
    REGISTER_SIMPLE_COMPONENT_SERIALIZE(size, StrFromFloat3)
    REGISTER_SIMPLE_COMPONENT_DESERIALIZE(size, StrToFloat3)
END_REGISTER_SIMPLE_COMPONENT(size)
