#include "CGEKComponentLight.h"

REGISTER_COMPONENT(pointlight)
    REGISTER_COMPONENT_DEFAULT_VALUE(radius, 0.0f)
    REGISTER_COMPONENT_SERIALIZE(pointlight)
        REGISTER_COMPONENT_SERIALIZE_VALUE(radius, StrFromFloat)
    REGISTER_COMPONENT_DESERIALIZE(pointlight)
        REGISTER_COMPONENT_DESERIALIZE_VALUE(radius, StrToFloat)
END_REGISTER_COMPONENT(pointlight)
