#include "CGEKComponentColor.h"

REGISTER_SIMPLE_COMPONENT(color, float4(1.0f, 1.0f, 1.0f, 1.0f))
    REGISTER_SIMPLE_COMPONENT_SERIALIZE(color, StrFromFloat4)
    REGISTER_SIMPLE_COMPONENT_DESERIALIZE(color, StrToFloat4)
END_REGISTER_SIMPLE_COMPONENT(color)
