#include "CGEKComponentMass.h"

REGISTER_COMPONENT(mass)
    REGISTER_COMPONENT_DEFAULT_VALUE(value, 0.0f)
    REGISTER_COMPONENT_SERIALIZE(mass)
        REGISTER_COMPONENT_SERIALIZE_VALUE(value, StrFromFloat)
    REGISTER_COMPONENT_DESERIALIZE(mass)
        REGISTER_COMPONENT_DESERIALIZE_VALUE(value, StrToFloat)
END_REGISTER_COMPONENT(mass)
