#include "CGEKComponentColor.h"

REGISTER_COMPONENT(color)
    REGISTER_COMPONENT_DEFAULT_VALUE(value, float4(1.0f, 1.0f, 1.0f, 1.0f))
    REGISTER_COMPONENT_SERIALIZE(color)
        REGISTER_COMPONENT_SERIALIZE_VALUE(value, StrFromFloat4)
    REGISTER_COMPONENT_DESERIALIZE(color)
        REGISTER_COMPONENT_DESERIALIZE_VALUE(value, StrToFloat4)
END_REGISTER_COMPONENT(color)
