#include "CGEKComponentSize.h"

REGISTER_COMPONENT(size)
    REGISTER_COMPONENT_DEFAULT_VALUE(value, 1.0f)
    REGISTER_COMPONENT_SERIALIZE(size)
        REGISTER_COMPONENT_SERIALIZE_VALUE(value, StrFromFloat)
    REGISTER_COMPONENT_DESERIALIZE(size)
        REGISTER_COMPONENT_DESERIALIZE_VALUE(value, StrToFloat)
END_REGISTER_COMPONENT(size)
