name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      os_matrix: ${{ steps.set_list.outputs.os_list }}
    steps:
      - id: set_list
        run: echo 'os_list=["ubuntu-latest", "windows-latest"]' >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.setup.outputs.os_matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install X11 dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev
      - name: Clone Slang (Recursive)
        run: git clone --depth 1 --branch v2026.2.2 --recursive https://github.com/shader-slang/slang.git ${{github.workspace}}/slang
      - name: Build and install Slang (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $prefix = "${{ github.workspace }}/slang/install"
          $prefix = $prefix -replace '\\', '/'
          cmake -S ${{github.workspace}}/slang -B ${{github.workspace}}/slang/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSLANG_ENABLE_TESTS=OFF -DSLANG_ENABLE_EXAMPLES=OFF -DSLANG_ENABLE_RHI=OFF -DSLANG_ENABLE_SPIRV_TOOLS=OFF -DCMAKE_INSTALL_PREFIX="$prefix"
          cmake --build ${{github.workspace}}/slang/build --config ${{env.BUILD_TYPE}} --target install
      - name: Build and install Slang (Linux)
        if: runner.os != 'Windows'
        run: |
          prefix="${{ github.workspace }}/slang/install"
          cmake -S ${{github.workspace}}/slang -B ${{github.workspace}}/slang/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSLANG_ENABLE_TESTS=OFF -DSLANG_ENABLE_EXAMPLES=OFF -DSLANG_ENABLE_RHI=OFF -DSLANG_ENABLE_SPIRV_TOOLS=OFF -DCMAKE_INSTALL_PREFIX="$prefix"
          cmake --build ${{github.workspace}}/slang/build --config ${{env.BUILD_TYPE}} --target install
      - name: Force Slang Target Alias
        run: |
          DIR="${{github.workspace}}/slang/install/lib/cmake/slang"
          mkdir -p "$DIR"
          cat > "$DIR/slang-config.cmake" <<EOF
          if(NOT TARGET slang)
            add_library(slang SHARED IMPORTED GLOBAL)
            set_target_properties(slang PROPERTIES \
              INTERFACE_INCLUDE_DIRECTORIES "${{github.workspace}}/slang/install/include"\
              IMPORTED_LOCATION "${{github.workspace}}/slang/install/bin/slang.dll"\
              IMPORTED_IMPLIB "${{github.workspace}}/slang/install/lib/slang.lib"\
            )
            if(UNIX)
              set_target_properties(slang PROPERTIES \
                IMPORTED_LOCATION "${{github.workspace}}/slang/install/lib/libslang.so"\
              )
            endif()
          endif()
          set(slang_FOUND TRUE)
          set(slang_SOURCE_DIR "${{github.workspace}}/slang")
          EOF
      - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.4.304.1
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    - name: Print Vulkan SDK env (Windows only)
      if: runner.os == 'Windows'
      run: |
        echo "VULKAN_SDK=$Env:VULKAN_SDK"
        echo "VULKAN_SDK=$Env:VULKAN_SDK" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "Vulkan_INCLUDE_DIR=$Env:VULKAN_SDK\Include" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "Vulkan_LIBRARY=$Env:VULKAN_SDK\Lib" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Print Vulkan SDK env (Linux only)
      if: runner.os == 'Linux'
      run: |
        echo "VULKAN_SDK=$VULKAN_SDK"
        echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
        echo "Vulkan_INCLUDE_DIR=$VULKAN_SDK/include" >> $GITHUB_ENV
        echo "Vulkan_LIBRARY=$VULKAN_SDK/lib" >> $GITHUB_ENV
    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build 
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
        -DCMAKE_PREFIX_PATH="${{github.workspace}}/slang/install"
        -Dslang_DIR="${{github.workspace}}/slang/install/lib/cmake/slang"
        -DFETCHCONTENT_TRY_FIND_PACKAGE_MODE=ALWAYS
        -DVULKAN_SDK="${{ env.VULKAN_SDK }}" 
        -DSLANG_ROOT="${{github.workspace}}/slang/install"
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
