name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch Vulkan SDK version spec
      shell: bash
      run: |
        curl -o vulkan-sdk-config.json https://vulkan.lunarg.com/sdk/config/1.3.243.0/linux/config.json

    - name: Configure Vulkan SDK using the downloaded spec
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-config-file: vulkan-sdk-config.json
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

