name: Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Run tests (if present)
        run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
        working-directory: build
        continue-on-error: true